apiVersion: v1
kind: Service
metadata:
  name: cert-proxy-service
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.deployment.name }}
  type: ClusterIP
  clusterIP: {{ .Values.certProxy.proxyIp }}
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP