apiVersion: v1
kind: Service
metadata:
  name: cert-proxy-service
spec:
  selector:
    app.kubernetes.io/name: cert-proxy-nginx
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP