repository: docker.drift.inera.se/ntjp/

deployment:
  name: cert-proxy
  replicaCount: 1
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 256Mi

container:
  image:
    name: cert-proxy
    tag: # Override to supply another image tag to run
    pullPolicy: Always

certProxy:
  proxyIp: 10.111.0.10
  proxyServer: proxy.example.com
  proxyPort: 443
  targetServer: www.example.com
  targetPort: 443
  healthPort: 80

serverCertificate:
  secretName: # Override to supply the certificate for incoming traffic
  mountPath: /etc/nginx/ssl-in
  pemFile: tls.crt
  pemKeyFile: tls.key
clientCertificate:
  secretName: # Override to supply the certificate for outgoing traffic
  mountPath: /etc/nginx/ssl-out
  pemFile: tls.crt
  pemKeyFile: tls.key
trust:
  secretName: # Override to supply the trusted certificate
  mountPath: /etc/nginx/ssl-out
  pemFile: ca.crt

environment:
  variables:
    _default_config_maps:
      - cert-proxy-configmap-default
    config_maps:
    # Override to supply your own maps.
    secrets:
    # Override to supply your own secrets.